### ISSUE TITLE
Please find more Bot than by this API

### ISSUE THREAD

**Issue by M-DinhHoangViet** [TheYoBots/libot-lb#19]
https://lichess.org/api/team/{teamId}/users

**Comment by M-DinhHoangViet** [comment]
https://lichess.org/api#tag/Teams/operation/teamIdUsers

**Comment by TheYoBots** [comment]
What's the question? What are you trying to do? What do you want me to do?

I'm sorry, but the question isn't really clear. Could you maybe provide more information?

**Comment by M-DinhHoangViet** [comment]
https://lichess.org/api/team/lichess-bots/users
Can you find more Bots with this link ?

**Comment by TheYoBots** [comment]
I've already added all bots from that team into the [available_bots.txt](https://github.com/TheYoBots/libot-lb/blob/master/available_bots.txt) file. I've even got bots from various other teams that have many bots
