### ISSUE TITLE
I want to support leaderboard of bot on lishogi, lidraughts and playstrategy

### ISSUE THREAD

**Issue by M-DinhHoangViet** [TheYoBots/libot-lb#21]

**Comment by TheYoBots** [comment]
I don't think those sites have many bots eligible for the leaderboard. In lishogi for example 0 bots are eligible.

**Comment by M-DinhHoangViet** [comment]
So how can I do the same thing without https://github.com/lichess-org/berserk?

**Comment by TheYoBots** [comment]
This repository doesn't use [berserk](https://pypi.org/project/berserk/).

**Comment by M-DinhHoangViet** [comment]
Ok, but lishogi and etc not have

**Comment by TheYoBots** [comment]
Yes, berserk is for lichess not for other sites. What exactly is it that you want me to do?

**Comment by M-DinhHoangViet** [comment]
Ý tôi là mã này có thể sử dụng ```import lichess.api``` but can't use lishogi.api or playstrategy.api,..

**Comment by TheYoBots** [comment]
Yes, `import lichess.api` is from the package [python-lichess](https://pypi.org/project/python-lichess/) and there isn't a python package for lishogi/playstategy api.

**Comment by M-DinhHoangViet** [comment]
So can you follow my title?

**Comment by TheYoBots** [comment]
I'll have to think about this feature. Because there aren't too many bots on those sites and if I do implement this I feel almost all leaderboards will be empty.

**Comment by M-DinhHoangViet** [comment]
Ok
